### ISSUE TITLE
Adding food items pictures and data

### ISSUE THREAD

**Issue by chiragasawa** [adityabisoi/REST-fetch#60]
Adding Json data for food items with pictures so that it can be used in food application. which can be get using GET method.

**Are you working on this feature? (Yes/No)**
Yes

**Comment by paramsiddharth** [comment]
@chiragasawa Thank you for the issue. Since this feature is related to the `/photos` endpoint, you must extend the same for this feature. Use `/photos/food`. Since this addition is especially for food items, make sure to add support for query parameters that allow the retrieval of a specific category of food. For example, `GET /photos/food?taste=spicy`. You may proceed.

**Comment by chiragasawa** [comment]
Features has been added check the pull request and please merge my pull request.
